on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: ilammy/msvc-dev-cmd@v1
      - run: cmake -S src -B src/out/build -G Ninja -DCMAKE_BUILD_TYPE="RelWithDebInfo"
      - run: cmake --build src/out/build
