on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - amd64
          - amd64_x86
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          # Required for version stamping (`git describe`) to work.
          fetch-depth: 0
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      - run: cmake -S src -B src/out/build -G Ninja -DCMAKE_BUILD_TYPE="RelWithDebInfo" -DCMAKE_INSTALL_PREFIX:PATH=${{ github.workspace }}/src/out/install
      - run: cmake --build src/out/build
      - run: cmake --install src/out/build
      - uses: actions/upload-artifact@v2
        with:
          name: FlexASIO-${{ matrix.arch }}
          path: src/out/install/
