on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - msvc_config: arm64-Release
            msvc_arch: amd64_arm64
            build_type: RelWithDebInfo
          - msvc_config: arm64-Debug
            msvc_arch: amd64_arm64
            build_type: Debug
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          # Required for version stamping (`git describe`) to work.
          fetch-depth: 0
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.msvc_arch }}
      - run: cmake -S src -B src/out/build/${{ matrix.msvc_config }} -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_INSTALL_PREFIX:PATH=${{ github.workspace }}/src/out/install/${{ matrix.msvc_config }}
      - run: cmake --build src/out/build/${{ matrix.msvc_config }}
      - run: cmake --install src/out/build/${{ matrix.msvc_config }}
      - uses: actions/upload-artifact@v2
        with:
          name: FlexASIO-${{ matrix.msvc_config }}
          path: src/out/install/${{ matrix.msvc_config }}/
  installer:
    runs-on: windows-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          # Required for version stamping (`git describe`) to work.
          fetch-depth: 0
      - uses: actions/download-artifact@v2
        with:
          name: FlexASIO-arm64-Release
          path: src/out/install/arm64-Release
      - run: cmake -P installer.cmake
        working-directory: src
      - uses: actions/upload-artifact@v2
        with:
          name: FlexASIO-installer
          path: src/out/installer/*
